### ISSUE TITLE
The ToolBar witht the back and settings button shifts upwards . OUt of View

### ISSUE THREAD

**Issue by sandeepwww** [albinmathew/design-support-library-demo#1]
Please help me out. This happens only on devices 5.0>
It works fine on 4.X devices

**Comment by albinmathew** [comment]
Hi 
I found it working in my genymotion emulator running in 5.1, but this is a known issue for 5.0 devices , please refer to this link https://code.google.com/p/android/issues/detail?id=175240

**Comment by albinmathew** [comment]
You can also look at this blog to learn more about new libraries 
https://medium.com/android-bites/first-steps-with-the-design-support-library-8dcf06230ddd
